# Stock market trend prediction

### This project focuses on analyzing Tesla’s stock price time series to detect and forecast market trends (bullish, bearish, or neutral). It begins with traditional statistical and technical indicator methods, then progressively integrates advanced machine learning and deep learning algorithms to improve the accuracy and responsiveness of trend detection. The outcome is a comparative study and prototype capable of automatically identifying the current trend and predicting potential reversals.

By Thomas Jin, Thibault Gauthé, Yijia Zhang

In [9]:
import yfinance as yf
import pandas as pd
import ta

In [10]:
data = yf.download("TSLA", start="2015-01-01", end="2025-01-01", interval="1d")
data.head()

C:\Users\TJN22\AppData\Local\Temp\ipykernel_13252\26741526.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download("TSLA", start="2015-01-01", end="2025-01-01", interval="1d")
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker           TSLA       TSLA       TSLA       TSLA      TSLA
Date
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500

### Nettoyage du dataset

In [11]:
data.describe()

Price         Close         High          Low         Open        Volume
Ticker         TSLA         TSLA         TSLA         TSLA          TSLA
count   2516.000000  2516.000000  2516.000000  2516.000000  2.516000e+03
mean     115.679423   118.250154   112.986545   115.701436  1.123131e+08
std      114.226440   116.887822   111.485181   114.312114  7.407088e+07
min        9.578000    10.331333     9.403333     9.488000  1.062000e+07
25%       17.185167    17.481667    16.889166    17.177167  6.681885e+07
50%       28.505667    28.806000    27.349999    28.413666  9.284585e+07
75%      220.205002   225.354996   215.336670   220.925003  1.297886e+08
max      479.859985   488.540009   457.510010   475.899994  9.140820e+08

In [14]:
data.isnull().sum()

Price   Ticker
Close   TSLA      0
High    TSLA      0
Low     TSLA      0
Open    TSLA      0
Volume  TSLA      0
dtype: int64